# 2D Arithmetic

In [3]:
import numpy as np
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print(np_mat * 2)
print("\n")
print(np_mat + np.array([10, 10]))
print("\n")
print(np_mat + np_mat)
# np_baseball is coded for you; it's again a 2D numpy array with 3 columns representing height, weight and age.

[[ 2  4]
 [ 6  8]
 [10 12]]


[[11 12]
 [13 14]
 [15 16]]


[[ 2  4]
 [ 6  8]
 [10 12]]


In [19]:
# baseball is available as a regular list of lists
baseball = [[180, 78.4, 1.5],
            [215, 102.7, 1.6],
            [210, 98.5, 1.7],
            [188, 75.2,1.8]]

# updated is available as 2D numpy array
updated = [[180, 78.4, 0.0],
            [215, 102.7, 0.1],
            [210, 98.5, 0.2],
            [188, 75.2, 0.3]]

In [20]:
# Import numpy package
import numpy as np

In [21]:
# Create np_baseball (3 cols)
np_baseball = np.array(baseball)

In [22]:
# Print out addition of np_baseball and updated
print(np_baseball + updated)

[[360.  156.8   1.5]
 [430.  205.4   1.7]
 [420.  197.    1.9]
 [376.  150.4   2.1]]


In [23]:
# Create numpy array: conversion
conversion = np.array([0.0254, 0.453592, 1.0])

In [24]:
# Print out product of np_baseball and conversion
print(np_baseball * conversion)

[[ 4.572     35.5616128  1.5      ]
 [ 5.461     46.5838984  1.6      ]
 [ 5.334     44.678812   1.7      ]
 [ 4.7752    34.1101184  1.8      ]]
